[metadata]
creation_date = "2023/02/28"
integration = ["endpoint"]
maturity = "production"
min_stack_comments = "New fields added: required_fields, related_integrations, setup"
min_stack_version = "8.3.0"
updated_date = "2023/03/22"

[rule]
author = ["Elastic"]
description = """
Message of the day (MOTD) is the message that is presented to the user when a user connects to 
a Linux server via SSH or a serial connection. Linux systems contain several default MOTD files
located in the "/etc/update-motd.d/" and "/usr/lib/update-notifier/" directories. These scripts run 
as the root user every time a user connects over SSH or a serial connection. Adversaries may create
malicious MOTD files that grant them persistence onto the target every time a user connects to the 
system by executing a backdoor script or command. This rule detects the execution of potentially 
malicious processes through the MOTD utility. 
"""
from = "now-9m"
index = ["logs-endpoint.events.*", "endgame-*"]
language = "eql"
license = "Elastic License v2"
name = "Suspicious Process Spawned from MOTD Detected"
note = """## Triage and analysis

### Investigating Suspicious Process Spawned from MOTD Detected

Detection alerts from this rule indicate that a potentially malicious or at least suspicious process was spawned from a MOTD script, which is not likely to occur as default benign behavior. Administrators might alter or create new MOTD files in these directories, so investigation to see whether the file is malicious or benign is vital. The first files to check can be found here:
- /etc/update-motd.d/
- /usr/lib/update-notifier/

The file(s) created within these directories may contain links to executables, scripts or may just run a specific command. It is important to follow the references from these files to the possibly newly created scripts that are executed in order to figure out exactly which commands/programs are being executed.

Analyzing the process tree to see which user added or altered the specific motd script might be valuable. In case this behavior originates from a new MOTD file, the "Potential Persistence Through MOTD File Creation Detected" rule might deliver more insight into the creation of this file. 

### Related Rules

- Potential Persistence Through MOTD File Creation Detected - 96d11d31-9a79-480f-8401-da28b194608f

### Response and remediation

- Initiate the incident response process based on the outcome of the triage.
- Isolate the involved host to prevent further post-compromise behavior.
- Investigate credential exposure on systems compromised or used by the attacker to ensure all compromised accounts are identified. Reset passwords for these accounts and other potentially compromised credentials, such as email, business systems, and web services.
- Delete the MOTD files or restore them to the original configuration.
- Run a full antimalware scan. This may reveal additional artifacts left in the system, persistence mechanisms, and malware components.
- Determine the initial vector abused by the attacker and take action to prevent reinfection through the same vector.
- Leverage the incident response data and logging to improve the mean time to detect (MTTD) and the mean time to respond (MTTR).
"""
references = [
    ""
]
risk_score = 73
rule_id = "4ec47004-b34a-42e6-8003-376a123ea447"
severity = "high"
tags = ["Elastic", "Host", "Linux", "Threat Detection", "Persistence", "Elastic Endgame", "Investigation Guide"]
timestamp_override = "event.ingested"
type = "eql"

query = '''
process where host.os.type == "linux" and 
event.type == "start" and event.action : ("exec", "exec_event") and
process.parent.executable : ("/etc/update-motd.d/*", "/usr/lib/update-notifier/*") and
process.executable : ("*sh", "python*", "perl", "php*")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1037"
name = "Boot or Logon Initialization Scripts"
reference = "https://attack.mitre.org/techniques/T1037/"



[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"
